services:
  ocafrontend:
    image: amikom/ocafrontend:1.0.0
    container_name: ocafrontend
    restart: always
    ports:
      - "80:3000"
      - "3000:3000"
    build:
      context: .
      dockerfile: dockerfile